import os
import json
from pathlib import Path
from pathlib import Path

# Change this once if you move your project
BASE_DIR = Path("D:/VS/Code Revive Agent")

CONFIG_DIR = BASE_DIR / "config"
OUTPUT_DIR = BASE_DIR / "output"


def load_directory_roles(config_dir):
    """Load the declarative directory roles map from config/directory_roles.json."""
    roles_path = CONFIG_DIR  / "directory_roles.json"
    if not roles_path.is_file():
        raise FileNotFoundError(f"Missing {roles_path}. Please create this file with directory mappings.")
        
    with open(roles_path, "r") as f:
        return json.load(f)

def load_project_report():
    """Load the project report generated by scan_files.py."""
    report_path = OUTPUT_DIR / "project_report.json"
    if not report_path.is_file():
        raise FileNotFoundError(f"Missing {report_path}. Run scan_files.py first.")
        
    with open(report_path, "r") as f:
        return json.load(f)


def determine_project_root(package_analysis):
    """Safely determine project root using pathlib based on absolute vs relative paths."""
    if not package_analysis:
        return None
        
    first_pkg = package_analysis[0]
    rel_path = Path(first_pkg.get("file_path", ""))
    abs_path = Path(first_pkg.get("absolute_path", ""))
    
    # If rel_path is "client/package.json" (2 parts), the root is 1 level up from the absolute file's parent.
    try:
        levels_to_go_up = len(rel_path.parts) - 1
        project_root = abs_path.parents[levels_to_go_up]
        if project_root.is_dir():
            return project_root
    except Exception:
        pass
    return None

def analyze_filesystem_structure(base_path, evidence_log, directory_roles):
    """Scan the filesystem to map out domains and internal structures."""
    domains = {}
    top_level_dirs = []
    ignore_dirs = {".git", "node_modules"}

    # 1. Identify top-level domains (client, server, or just root)
    for item in base_path.iterdir():
        if item.is_dir() and item.name not in ignore_dirs:
            top_level_dirs.append(item.name)
            
            domain_role = "unknown"
            if item.name.lower() in directory_roles.get("frontend", []):
                domain_role = "frontend"
                evidence_log.append(f"Found frontend domain via directory: {item.name}")
            elif item.name.lower() in directory_roles.get("backend", []):
                domain_role = "backend"
                evidence_log.append(f"Found backend domain via directory: {item.name}")
                
            if domain_role != "unknown":
                domains[item.name] = {
                    "role": domain_role,
                    "directories_found": {}
                }

    # Fallback: If no explicit frontend/backend folders found, assume monolithic root
    if not domains:
        domains["root"] = {
            "role": "monolith-or-root",
            "directories_found": {}
        }
        evidence_log.append("No explicit client/server directories found. Treating project root as primary domain.")

    # 2. Map internal structural directories for each discovered domain
    for domain_name, domain_data in domains.items():
        domain_path = base_path if domain_name == "root" else base_path / domain_name
        
        if domain_path.is_dir():
            for sub_item in domain_path.iterdir():
                if sub_item.is_dir() and sub_item.name not in ignore_dirs:
                    # Check what structural role this sub-directory plays
                    for role, keywords in directory_roles.items():
                        # Skip frontend/backend as we already mapped domains
                        if role in ["frontend", "backend"]:
                            continue
                            
                        if sub_item.name.lower() in keywords:
                            if role not in domain_data["directories_found"]:
                                domain_data["directories_found"][role] = []
                            # Store relative path
                            rel_sub = f"{domain_name}/{sub_item.name}" if domain_name != "root" else sub_item.name
                            domain_data["directories_found"][role].append(rel_sub)
                            
    return domains, sorted(top_level_dirs)

def map_packages_to_domains(domains, package_analysis, evidence_log):
    """Attach package.json evidence to the domains we found on the filesystem."""
    for pkg in package_analysis:
        rel_path = Path(pkg.get("file_path", ""))
        
        # Determine which domain this package belongs to
        if len(rel_path.parts) > 1:
            domain_name = rel_path.parts[0]
        else:
            domain_name = "root"
            
        if domain_name in domains:
            domains[domain_name]["package_file"] = str(rel_path)
            
            # If the domain role was unknown/root, try to guess from dependencies
            if domains[domain_name]["role"] == "monolith-or-root":
                deps = pkg.get("dependencies", {})
                dev_deps = pkg.get("dev_dependencies", {})
                all_deps = list(deps.keys()) + list(dev_deps.keys())
                
                if any(tech in all_deps for tech in ["react", "vue", "next"]):
                    domains[domain_name]["role"] = "frontend"
                    evidence_log.append(f"Inferred {domain_name} as frontend based on package dependencies (e.g., react/vue).")
                elif any(tech in all_deps for tech in ["express", "django", "mongoose"]):
                    domains[domain_name]["role"] = "backend"
                    evidence_log.append(f"Inferred {domain_name} as backend based on package dependencies.")

def categorize_important_files_by_domain(important_files, domains):
    """Group important files strictly by their physical location in the domains."""
    categorized = {domain: [] for domain in domains.keys()}
    categorized["unmapped"] = []
    
    for file_str in important_files:
        file_path = Path(file_str)
        mapped = False
        
        for domain_name in domains.keys():
            # If domain is root, everything technically belongs to it, but we handle it safely
            if domain_name != "root" and file_path.parts[0] == domain_name:
                categorized[domain_name].append(file_str)
                mapped = True
                break
                
        if not mapped:
            if "root" in domains:
                categorized["root"].append(file_str)
            else:
                categorized["unmapped"].append(file_str)
                
    return categorized

def deduce_architecture(domains, evidence_log):
    """Determine architecture and generate a confidence score."""
    roles_found = [data.get("role") for data in domains.values()]
    
    if "frontend" in roles_found and "backend" in roles_found:
        evidence_log.append("Detected both distinct frontend and backend roles.")
        return {"type": "client-server", "confidence": "high"}
        
    elif "frontend" in roles_found:
        return {"type": "standalone-frontend", "confidence": "medium"}
        
    elif "backend" in roles_found:
        return {"type": "standalone-backend", "confidence": "medium"}
        
    return {"type": "unknown-or-monolith", "confidence": "low"}

def main():
    # 1. Load Data
    try:
        directory_roles = load_directory_roles(CONFIG_DIR)
        report = load_project_report()
    except FileNotFoundError as e:
        print(e)
        return

    package_analysis = report.get("package_json_analysis", [])
    important_files = report.get("important_files", [])
    
    base_path = determine_project_root(package_analysis)
    
    # Validation: Ensure project root is resolved and valid
    if not base_path or not base_path.is_dir():
        print("Error: Could not resolve a valid project base path from report evidence.")
        return

    evidence_log = []

    # 2. Analyze (Filesystem First)
    domains, top_level_dirs = analyze_filesystem_structure(base_path, evidence_log, directory_roles)
    
    # 3. Augment with Package Evidence
    map_packages_to_domains(domains, package_analysis, evidence_log)
    
    # 4. Map Files & Finalize Architecture
    files_by_domain = categorize_important_files_by_domain(important_files, domains)
    architecture = deduce_architecture(domains, evidence_log)

    # 5. Build Output
    project_structure = {
        "project_name": report.get("project_name", "unknown"),
        "architecture": {
            "type": architecture["type"],
            "confidence": architecture["confidence"],
            "evidence": evidence_log
        },
        "top_level_directories": top_level_dirs,
        "domains": domains,
        "important_files_by_domain": files_by_domain
    }

    # 6. Save
    
    output_file = OUTPUT_DIR / "project_structure.json"
    with open(output_file, "w") as f:
        json.dump(project_structure, f, indent=4)

    print(f"\nProject structure report successfully saved to: {output_file}")


    print(f"\nProject structure report successfully saved to: {output_file}")

if __name__ == "__main__":
    main()